/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.*;
import java.awt.*;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import model.User;
import rmi.DonorService;
import rmi.DonationService;
import rmi.BloodRequestService;
import rmi.BloodInventoryService;

/**
 *
 * @author Magnifique
 */
public class DashboardForm extends javax.swing.JFrame {

    private DonorManagementForm donorManagementPanel;
    private DonationForm donationPanel;
    private BloodRequestPanel bloodRequestPanel;
    private BloodInventoryPanel bloodInventoryPanel;

    private CardLayout cardLayout;
    private User currentUser;

    // RMI Services
    private DonorService donorService;
    private DonationService donationService;
    private BloodRequestService bloodRequestService;
    private BloodInventoryService bloodInventoryService;

    public DashboardForm(User user) {
        this.currentUser = user;

        try {
            // Connect to RMI registry
            Registry registry = LocateRegistry.getRegistry("localhost", 5000);
            donorService = (DonorService) registry.lookup("donor");
            donationService = (DonationService) registry.lookup("donation");
            bloodRequestService = (BloodRequestService) registry.lookup("bloodRequest");
            bloodInventoryService = (BloodInventoryService) registry.lookup("bloodInventory");


            System.out.println("[Dashboard] ✅ Connected to DonorService and DonationService.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Failed to connect to RMI services.\n" + e.getMessage(),
                    "RMI Connection Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

        initComponents();
        this.setSize(1700, 1000);
        jPanel2.setPreferredSize(new Dimension(1100, 800));

        cardLayout = new CardLayout();
        jPanel2.setLayout(cardLayout);

        // Pass services to each form
        donorManagementPanel = new DonorManagementForm(currentUser, donorService);
        donationPanel = new DonationForm(currentUser, donorService, donationService);
        bloodRequestPanel = new BloodRequestPanel(currentUser, bloodRequestService);
        bloodInventoryPanel = new BloodInventoryPanel(bloodInventoryService);
        
        

        jPanel2.add(donorManagementPanel, "donorPanel");
        jPanel2.add(donationPanel, "donationPanel");
        jPanel2.add(bloodRequestPanel, "bloodRequestPanel");
        jPanel2.add(bloodInventoryPanel, "BloodInventory");

        welcomeLabel.setText("Welcome, " + currentUser.getUsername());
        setLocationRelativeTo(null);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        donorManagementBtn = new javax.swing.JButton();
        bloodInventoryButton = new javax.swing.JButton();
        donationTrackingBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        bloodRequestsBtn1 = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Blood Donation System - Dashboard");
        setFocusable(false);
        setPreferredSize(new java.awt.Dimension(1700, 990));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        mainPanel.setPreferredSize(new java.awt.Dimension(1200, 850));

        jPanel3.setBackground(new java.awt.Color(200, 30, 47));

        jLabel1.setBackground(new java.awt.Color(200, 30, 45));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BLOOD DONATION SYSTEM");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(200, 30, 45));

        donorManagementBtn.setBackground(new java.awt.Color(153, 153, 153));
        donorManagementBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        donorManagementBtn.setForeground(new java.awt.Color(200, 30, 45));
        donorManagementBtn.setText("Donor Management");
        donorManagementBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        donorManagementBtn.setBorderPainted(false);
        donorManagementBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        donorManagementBtn.setFocusPainted(false);
        donorManagementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donorManagementBtnActionPerformed(evt);
            }
        });

        bloodInventoryButton.setBackground(new java.awt.Color(153, 153, 153));
        bloodInventoryButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bloodInventoryButton.setForeground(new java.awt.Color(200, 30, 45));
        bloodInventoryButton.setText("Blood Stock");
        bloodInventoryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bloodInventoryButton.setFocusPainted(false);
        bloodInventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodInventoryButtonActionPerformed(evt);
            }
        });

        donationTrackingBtn.setBackground(new java.awt.Color(153, 153, 153));
        donationTrackingBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        donationTrackingBtn.setForeground(new java.awt.Color(200, 30, 45));
        donationTrackingBtn.setText("Donation Tracking");
        donationTrackingBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        donationTrackingBtn.setFocusPainted(false);
        donationTrackingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donationTrackingBtnActionPerformed(evt);
            }
        });

        logoutBtn.setBackground(new java.awt.Color(232, 76, 60));
        logoutBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setText("Logout");
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        bloodRequestsBtn1.setBackground(new java.awt.Color(153, 153, 153));
        bloodRequestsBtn1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bloodRequestsBtn1.setForeground(new java.awt.Color(200, 30, 45));
        bloodRequestsBtn1.setText("Blood Requests");
        bloodRequestsBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bloodRequestsBtn1.setFocusPainted(false);
        bloodRequestsBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodRequestsBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(donationTrackingBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                .addComponent(donorManagementBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bloodInventoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addComponent(bloodRequestsBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(donorManagementBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(donationTrackingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(bloodRequestsBtn1)
                .addGap(46, 46, 46)
                .addComponent(bloodInventoryButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 482, Short.MAX_VALUE)
                .addComponent(logoutBtn)
                .addGap(24, 24, 24))
        );

        welcomeLabel.setBackground(new java.awt.Color(200, 30, 45));
        welcomeLabel.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(0, 51, 102));
        welcomeLabel.setText("Welcome,");
        welcomeLabel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                welcomeLabelComponentHidden(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(1100, 800));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1274, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 817, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1782, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1782, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1016, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE))
        );

        mainPanel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bloodInventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodInventoryButtonActionPerformed
        
        CardLayout cl = (CardLayout) jPanel2.getLayout();
        cl.show(jPanel2, "BloodInventory"); 
    }//GEN-LAST:event_bloodInventoryButtonActionPerformed

    private void donationTrackingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donationTrackingBtnActionPerformed
      CardLayout cl = (CardLayout)(jPanel2.getLayout());
      cl.show(jPanel2, "donationPanel");

    }//GEN-LAST:event_donationTrackingBtnActionPerformed

    private void donorManagementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donorManagementBtnActionPerformed

        
       // Show the Donor Management Panel within the dashboard
        cardLayout.show(jPanel2, "donorPanel");


        
    }//GEN-LAST:event_donorManagementBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        
        int response = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to logout?",
            "Confirm Logout",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (response == JOptionPane.YES_OPTION) {
            // Return to login screen
            LoginForm loginForm = new LoginForm();
            loginForm.setVisible(true);
            this.dispose(); // Close current dashboard
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void welcomeLabelComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_welcomeLabelComponentHidden

    }//GEN-LAST:event_welcomeLabelComponentHidden

    private void bloodRequestsBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodRequestsBtn1ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) jPanel2.getLayout();
        cl.show(jPanel2, "bloodRequestPanel"); 
    }//GEN-LAST:event_bloodRequestsBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            // TEMPORARY TEST USER - Replace with your actual user later
            User testUser = new User("AdminUser"); 
            new DashboardForm(testUser).setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bloodInventoryButton;
    private javax.swing.JButton bloodRequestsBtn1;
    private javax.swing.JButton donationTrackingBtn;
    private javax.swing.JButton donorManagementBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
